### ISSUE TITLE
Locations.xml.aspx API documentation?

### ISSUE THREAD

**Issue by TrentBartlem** [ccpgames/eveonline-third-party-documentation#117]
Seems to be missing.

**Comment by JimiC** [comment]
A stub page has been created for `Character` and `Corporation`. Anyone feel free to contribute on them.

**Comment by JimiC** [comment]
Locations for Character was added in #138.

**Comment by Regner** [comment]
Sorry, still missing corporations. DERP!

**Comment by JimiC** [comment]
Close pls. All work is done.

**Comment by Regner** [comment]
Thanks for the poke. :) Really appreciate it.
