### ISSUE TITLE
Update mkdocs structure to new format.

### ISSUE THREAD

**Issue by JimiC** [ccpgames/eveonline-third-party-documentation#127]
According to mkdocs the current structure we use in mkdocs.yaml is deprecated and will be removed in an upcoming release.

Figure this is a time sensitive issue so I kinda started working on it.

@Regner 
Just need your approval to submit a PR.

**Comment by Regner** [comment]
That would be wonderful!

**Comment by JimiC** [comment]
While I'm at it, I would like to propose an new tree structure (see images below).

![old](https://cloud.githubusercontent.com/assets/1716442/14078927/5f7ae552-f502-11e5-8a7e-d32800ee62a4.png)
![new](https://cloud.githubusercontent.com/assets/1716442/14078930/612efd02-f502-11e5-99f0-2240f953e0ed.png)

**Comment by Regner** [comment]
That looks awesome!
