### ISSUE TITLE
Add a Run in Postman button?

### ISSUE THREAD

**Issue by Regner** [ccpgames/eveonline-third-party-documentation#129]
What do you all think about adding a Run in Postman button?

I have put together two collections, one for CREST and one for the XML API. The CREST one is still missing the character stuff and the XML API is still missing the corp stuff. Will finish them up tomorrow or something.

CREST
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/b5e0b9ea6c8d9ab83caf#?env%5BTQ%20Public%20CREST%5D=W3sia2V5IjoiYmFzZV91cmwiLCJ2YWx1ZSI6Imh0dHBzOi8vcHVibGljLWNyZXN0LmV2ZW9ubGluZS5jb20iLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY29uc3RlbGxhdGlvbl9pZCIsInZhbHVlIjoiMjAwMDAwMDEiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoicmVnaW9uX2lkIiwidmFsdWUiOiIxMDAwMDAwMiIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJhbGxpYW5jZV9pZCIsInZhbHVlIjoiNDM0MjQzNzIzIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InN5c3RlbV9pZCIsInZhbHVlIjoiMzAwMDAxNDIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5Ijoid2FyX2lkIiwidmFsdWUiOiI2NDgzIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImRvZ21hX2F0dHJpYnV0ZV9pZCIsInZhbHVlIjoiMzAiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiZG9nbWFfZWZmZWN0X2lkIiwidmFsdWUiOiIyNiIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJraWxsX2lkIiwidmFsdWUiOiI1Mjg2Nzk5NCIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJraWxsX2hhc2giLCJ2YWx1ZSI6ImU3YTZmNDU3ZDljM2FlOTI3NjlmZjk4MzVmODk4MDliYzBjZWNlNjQiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiZ3JvdXBfaWQiLCJ2YWx1ZSI6IjIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoidHlwZV9pZCIsInZhbHVlIjoiNjM4IiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImNhdGVnb3J5X2lkIiwidmFsdWUiOiIxNiIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0b3VybmFtZW50X2lkIiwidmFsdWUiOiIyIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InRvdXJuYW1lbnRfc2VyaWVzX2lkIiwidmFsdWUiOiIxIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InRvdXJuYW1lbnRfbWF0Y2hfaWQiLCJ2YWx1ZSI6IjEiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoidG91cm5hbWVudF9yZWFsdGltZV9mcmFtZV9pZCIsInZhbHVlIjoiNSIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0b3VybmFtZW50X3RlYW1faWQiLCJ2YWx1ZSI6IjEiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9XQ==)

 XML API
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/a9ed5331184f5640609e#?env%5BTQ%20XML%20API%20Blank%5D=W3sia2V5IjoiYmFzZV91cmwiLCJ2YWx1ZSI6Imh0dHBzOi8vYXBpLmV2ZW9ubGluZS5jb20iLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY2hhcmFjdGVyX2lkX2xpc3QiLCJ2YWx1ZSI6IjkyMTY4OTA5LDk1NTM4OTIxIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImNoYXJhY3Rlcl9uYW1lc19saXN0IiwidmFsdWUiOiJDQ1AgRm94Rm91cixDQ1AgU25vd2VkSW4iLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY2hhcmFjdGVyX2lkIiwidmFsdWUiOiI5MjE2ODkwOSIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJ0eXBlX2lkX2xpc3QiLCJ2YWx1ZSI6IjU4NCw4MjQiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiYXBpX2tleSIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImFwaV92Y29kZSIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImV2ZW50X2lkc19saXN0IiwidmFsdWUiOiIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiY29udHJhY3RfaWQiLCJ2YWx1ZSI6IiIsInR5cGUiOiJ0ZXh0IiwiZW5hYmxlZCI6dHJ1ZX0seyJrZXkiOiJiZWZvcmVfa2lsbF9pZCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6InJvd19jb3VudCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImxvY2F0aW9uX2lkc19saXN0IiwidmFsdWUiOiIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoibWFpbF9pZHNfbGlzdCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6Im1haWxfZnJvbV9pZCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6Im9yZGVyX2lkIiwidmFsdWUiOiIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5Ijoibm90aWZpY2F0aW9uX2lkc19saXN0IiwidmFsdWUiOiIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoicGxhbmV0X2lkIiwidmFsdWUiOiIiLCJ0eXBlIjoidGV4dCIsImVuYWJsZWQiOnRydWV9LHsia2V5IjoiYmVmb3JlX3JlZl9pZCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfSx7ImtleSI6ImJlZm9yZV90cmFuc19pZCIsInZhbHVlIjoiIiwidHlwZSI6InRleHQiLCJlbmFibGVkIjp0cnVlfV0=)

**Comment by deadlybulb** [comment]
I think it's a good idea.  It's also an opportunity to document a few basic workflows (like journal walking).  The only downside I can see is that I don't know that API collections can be community maintained unless you're planning to create a team library, invite 3rd party devs, etc.  An alternative would be to have a community maintained Swagger or RAML file which someone from CCP periodically imports into Postman.

**Comment by Regner** [comment]
@jimpurbrick any chance it would be possible to generate a RAML or Swagger file from Crestmatic?

**Comment by jimpurbrick** [comment]
It's certainly possible to use the json-schema files produced by crestmatic in Swagger documentation: https://groups.google.com/forum/#!topic/swagger-swaggersocket/1MrITh-Kcdg

In an ideal world though, you don't need Swagger documentation for CREST: you start at the API root, make GET requests to read data, PUT requests to write data, POST requests to add to collections and hyperlinks which can be POSTed to are returned for any other non-CRUD operations. These non-CRUD operations can be documented in the descriptions of the fields containing the hyperlinks. The descriptions are returned by OPTIONS requests and so would be included in the crestmatic data.

If all operations are either CRUD or described via fields and all hyperlinks are returned by the server rather than being constructed, representation schema should be all you need. Swagger docus should be redundant for a well designed RESTful hypermedia API, which is what CREST should aspire to be.

**Comment by Regner** [comment]
While I agree the advantage with having a Swagger or RAML file is people can easily experiment with the API and see the results. That is what I looking for, a way to make that discovery a nicer human experience. Yes we can automate our applications, and while http://jimpurbrick.com/crestmatic/ is great it is not quiet the same as being able to open a page and immediately start exploring the API and seeing the results.

**Comment by jimpurbrick** [comment]
I agree that having an interactive way to explore the API is useful. crestexplorer currently allows that for GET requests jimpurbrick.com/crestexplorerjs/#https://crest.eveonline.com Extending it to add descriptions from OPTION requests and allow PUT and POST requests would make it more useful.
