### ISSUE TITLE
PDF build fails on RTD

### ISSUE THREAD

**Issue by JimiC** [ccpgames/eveonline-third-party-documentation#132]
Due to the usage of unicode character ★ and Japanese in the docs, the PDF build fails as it doesn't supports it.

**Comment by JimiC** [comment]
I've been trying hard to find a solution for this issue but it looks like it's more than I can bite.
I only reached a point where I could generate a partial PDF ([eveonline-third-party-documentation.pdf](https://github.com/ccpgames/eveonline-third-party-documentation/files/211171/eveonline-third-party-documentation.pdf)).
As you can see the result is not pretty as text extents beyond the layout border.
Even if we manage to fix this unicode issue I'm afraid the result will no be satisfying.

My proposal is to drop the PDF building entirely.

**Comment by Regner** [comment]
Yup. Agreed. Just going to leave the PDF build disabled. Don't see it as a thing we need. Thank you for your efforts. :)
