### ISSUE TITLE
Correct link to Image Server documentation

### ISSUE THREAD

**Issue by JimiC** [ccpgames/eveonline-third-party-documentation#143]
I know this doesn't belong here but it's much easier to get the attention of the involved ppl.

In [Resources web page](https://developers.eveonline.com/resource/resources) the link to the Image Server `Documentation` points to 404. The correct link is https://eveonline-third-party-documentation.readthedocs.io/en/latest/imageserver/ or https://eveonline-third-party-documentation.readthedocs.io/en/latest/imageserver/index.html

**Comment by Regner** [comment]
Fuuuuck. Will try and do this tomorrow. Thanks!

**Comment by JimiC** [comment]
@Regner Friendly reminder.

**Comment by Regner** [comment]
Thanks. :) I have updated all links to point to the new RTD .io domain and have removed the one link you're referencing. It was supposed to link to a section about the image export collection, not the image server. We don't have a section for the IEC so have just removed it for now.

**Comment by JimiC** [comment]
Oh, my bad. Didn't caught that. If you had said so I could just added a stub page in the docs for that.

**Comment by Regner** [comment]
Wasn't sure if we wanted docs on the IEC. It was added originally just to try and stub lots of stuff out, but I haven't really seen people ask for it so not sure it is needed.
