### ISSUE TITLE
Contracts API: reward attribute

### ISSUE THREAD

**Issue by GoldenGnu** [ccpgames/eveonline-third-party-documentation#158]
Contracts API documentation incorrectly states that the reward attribute is only used for courier contracts. It's very misleading, as that is not at all how the price/reward attributes are used.

The correct way to understand the price/reward attributes:
Price attribute = Acceptor pays ISK and Issuer gets ISK
Reward attribute = Acceptor gets ISK and Issuer pays ISK

Courier contracts can not have a price, but, Item Exchange contracts can have a reward or a price (one or the other). I did not test Auctions.

**Comment by ccp-zoetrope** [comment]
Pull requests are welcome 😃.
