### ISSUE TITLE
Missing info on corp account balances

### ISSUE THREAD

**Issue by baynex** [ccpgames/eveonline-third-party-documentation#166]
The notes on the corp_accountbalance page notes the following

> accountKey: This is always 1000 for a character’s account balance as opposed to a corporation, where accountKey ranges from 1000 to 1006 for the seven corporate wallet divisions.

I am seeing another accountKey on my corporation's info. '10000', is this possibly market escrow?

**Comment by polarina** [comment]
I believe accountKey 10000 is the DUST wallet.

**Comment by Regner** [comment]
Yea, 10,000 should be DUST.

**Comment by baynex** [comment]
Ah, I see. I'd suggest adding a note on the page but with DUST closing shortly I imagine this will be removed anyway.
