### ISSUE TITLE
All Stations pull

### ISSUE THREAD

**Issue by Mezoti** [ccpgames/eveonline-third-party-documentation#171]
Hi
Watch out noob question. ;-)

I have been tying to make an pull for all stations in eve, NPC and Conquerable stations, i would be happy if fome one all ready have make this kind of scrips og pull so i can use it in Goggle speadsheet.
The information i look for is a minimum of RegionID, RegionName, solarSystemID, stationID, stationName.
Hope some one have made this all ready, and have just missed it in my search.

Best Regards
Mezoti

**Comment by deadlybulb** [comment]
Suggest you post your question here:

https://forums.eveonline.com/default.aspx?g=topics&f=263

you'll get a quicker answer

**Comment by polarina** [comment]
You can combine the station list from the SDE with the eve/ConquerableStationList.xml.aspx XML API endpoint.
