### ISSUE TITLE
Accept version unclear - add example call

### ISSUE THREAD

**Issue by bahrmichael** [ccpgames/eveonline-third-party-documentation#179]
I tried to follow the [docs](https://eveonline-third-party-documentation.readthedocs.io/en/latest/crest/versioning.html) for retrieving a specific API version. Both with GET and POST (the latter failed). I don't understand how it should be done and assume others might be as well. Do I have to call the POST differently or am doing something basically wrong?

```
Method: GET
URL: https://crest-tq.eveonline.com/
Header: 
   Accept: application/vnd.ccp.eve.Api-v2+json

Status: 200 OK
Result Header: "Content-Type", "application/vnd.ccp.eve.Api-v5+json; charset=utf-8"
```

```
Method: POST
URL: https://crest-tq.eveonline.com/
Header: 
   Accept: application/vnd.ccp.eve.Api-v2+json

Status: 400 Bad Request
Body:
{
  "message": "Did not find handle function to match POST None application/vnd.ccp.eve.Api-v2+json for class Api",
  "key": "noHandlerMatch",
  "exceptionType": "BadRequestError"
}
```

Tried other endpoints as well.

Can you point me in the right direction? Let's also add that info for others.

**Comment by polarina** [comment]
Shouldn't the header be `Accept: application/vnd.ccp.eve.Api-v2+json`? Remove the quotes and the comma.

**Comment by bahrmichael** [comment]
Yes, I just used another notation. Sorry for the confusion.

**Comment by bahrmichael** [comment]
Currently trying to reproduce that with curl (use Postman before).

**Comment by polarina** [comment]
It would seem that `application/vnd.ccp.eve.Api-v5+json` is the only supported MIME type for the root, which is why it's not accepting your header.

**Comment by bahrmichael** [comment]
How do you find out about the supported MIME types? Did not find any through OPTIONS.

Confirmed with curl:

```
$ curl -i -H "Accept: application/vnd.ccp.eve.Api-v1+json" https://crest-tq.eveonline.com/
HTTP/1.1 200 OK
Server: nginx/1.8.1
Date: Mon, 04 Jul 2016 17:26:40 GMT
Content-Type: application/vnd.ccp.eve.Api-v5+json; charset=utf-8
Content-Length: 2393
Connection: keep-alive
Vary: Accept-Encoding
Access-Control-Allow-Headers: AUTHORIZATION, X-REQUESTED-WITH, CONTENT-TYPE, ACCEPT
Access-Control-Max-Age: 1728000
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, HEAD, OPTIONS
Access-Control: allow <*>
Access-Control-Expose-Header: CONTENT-TYPE
Cache-Control: max-age=20
X-Cache-Status: EXPIRED
```

**Comment by polarina** [comment]
Look at the body from the OPTIONS call. It lists the accessible endpoints along with their MIME types.

**Comment by bahrmichael** [comment]
Got it, the [current body](http://pastebin.com/Pa0vhdCR) shows only one accepted version Api-v5+json. But that also means there is no way to test it yet?

**Comment by bahrmichael** [comment]
I've added some info on that to my fork, will make a PR to the end of the week.

**Comment by polarina** [comment]
You can try out the alliance list endpoint, which currently has `v1` and `v2` if I recall correctly.

**Comment by bahrmichael** [comment]
Correct, thanks for the info. You can close this issue. The information gained here will be put into the next PR.
