### ISSUE TITLE
/tournaments/ - expected behavior?

### ISSUE THREAD

**Issue by jonobrien** [ccpgames/eveonline-third-party-documentation#199]
so the root is fine, parsing to [https://crest-tq.eveonline.com/tournaments/1/](https://crest-tq.eveonline.com/tournaments/1/) as given, leads to an error:
`{"message": "Unknown resource", "isLocalized": false, "key": "noSuchStat", "exceptionType": "ForbiddenError"}`

root returns json:
href returned for id: 1-14
error occurs on: 1,2,3,4,5
seems to be ok: 6-14

but manually typing [https://crest-tq.eveonline.com/tournaments/1/series/](https://crest-tq.eveonline.com/tournaments/1/series/) is fine, is this expected behavior?

if I go to `../15/` I also get the above error, but `../15/series/` I get 
`{"message": "Unknown tournament", "isLocalized": false, "key": "noSuchTournament", "exceptionType": "ForbiddenError"}`

as I should as that doesn't exist, but `Unknown resource` seems incorrect.

**Comment by CarbonAlabel** [comment]
This repo is for the docs themselves, not CREST, so if you're experiencing bugs with it, a better option might be to submit a [bug report](https://community.eveonline.com/support/bug-reports/) and then poke a relevant developer with the report's ID until they fix it.

About the issue itself, there was some talk about this in #devfleet on Tweetfleet Slack, and I believe that we were told it might get fixed before the AT?

**Comment by jonobrien** [comment]
well it `is` undocumented, and I saw this as a relevant place to possibly document it.

I was going to formally submit a report if someone knew it was one, but since it is undocumented I thought it better to keep some ticket strain off CCP if I could.
