### ISSUE TITLE
Crest documentation created with Swagger

### ISSUE THREAD

**Issue by mentos1386** [ccpgames/eveonline-third-party-documentation#209]
I just found out Swagger, it's a tool for making REST API documentation. Documentation can be very easily written (http://editor.swagger.io/#/) and provides interactive tool to "try" resources where you get live response instead of current static response which can be outdated. I think this would be much better than current CREST documentation. 

Downside is that it isn't a part of readthedocs.io

[Swagger.io](http://swagger.io/)

**Comment by biow0lf** [comment]
I think that CREST documentation in Swagger format is good, but this is not right place for it.

But, if you  (@mentos1386) interested in it, part of it done at https://github.com/biow0lf/swagger-eveonline-crest-api

This is ruby app which are generating CREST documentation in Swagger 2.0 specification.

**Comment by deadlybulb** [comment]
You could add your swagger.json in this GitHub project instead of in the generated docs.  It would be nice to have a community maintained swagger.json we could all reference.

**Comment by mentos1386** [comment]
I gave it try,  this is some preview of how it would look [Gist](https://gist.github.com/mentos1386/a6127300f32c636c583effd4b14eedf8). Copy & Paste it  [here](http://editor.swagger.io/#/edit) to give it a try.

I went with yaml, as it is more readable than json in my opinion.

**Comment by deadlybulb** [comment]
Checking this out now.  Here's a direct link if you want to avoid cut and paste into the editor:

https://rawgit.com/mentos1386/a6127300f32c636c583effd4b14eedf8/raw/7461f668a71d8714c99396d05775edef85742ea1/eve-crest-swagger.yaml

**Comment by deadlybulb** [comment]
I think this is fine as a start, especially considering that we have nothing at the moment.  If you wanted to be more complete, you should document all the possible return codes for each endpoint, as well as GET vs. PUT vs. OPTIONS, etc. (most will only support GET and OPTIONS).   To start, you might just pick one endpoint and document all the variants.  Then leave the other endpoints to other contributors or other PRs.

**Comment by ccp-zoetrope** [comment]
CREST is on its way out and [ESI](https://esi.tech.ccp.is/latest/) is Swagger based so no CREST documentation will be made using Swagger.
