### ISSUE TITLE
Rates and limits 

### ISSUE THREAD

**Issue by antihax** [ccpgames/eveonline-third-party-documentation#211]
Is there any updated information on rates and limits for each resource or are the currently published values accurate?

**Comment by CarbonAlabel** [comment]
Should be accurate. Why are you asking?

**Comment by jonobrien** [comment]
check the headers :wink:

**Comment by Regner** [comment]
The headers don't really say anything about rate limits.

The rate limits listed in the docs right now should be accurate however.

**Comment by antihax** [comment]
Awesome.

**Comment by jonobrien** [comment]
edited
