### ISSUE TITLE
Links manually added in HTML tables don't work properly

### ISSUE THREAD

**Issue by deadlybulb** [ccpgames/eveonline-third-party-documentation#23]
Example:

http://eveonline-third-party-documentation.readthedocs.org/en/latest/xmlapi/endpoints/#marketorders

The superscript links in the "Result Data" section are supposed to link to other pages, but they fail because the live site adds "latest" to the link but the dev site doesn't have this.  So the link:

http://eveonline-third-party-documentation.readthedocs.org/en/xmlapi/enumerations/#order-state

fails because it should be:

http://eveonline-third-party-documentation.readthedocs.org/en/latest/xmlapi/enumerations/

Probably works fine if these are markdown tables instead.

**Comment by whinis** [comment]
Should be fixed in https://github.com/Regner/eveonline-third-party-documentation/pull/3 However github is stupid

**Comment by deadlybulb** [comment]
Nice!

**Comment by Regner** [comment]
This was fixed in #24
