### ISSUE TITLE
null refresh_token

### ISSUE THREAD

**Issue by bbenham** [ccpgames/eveonline-third-party-documentation#255]
3/5/2017,  same call that worked all week is returning json token data with a null refresh_token field.  
https://login.eveonline.com/oauth/token

Response:
"{"access_token":"3Nx4ugW7S......","token_type":"Bearer","expires_in":1200,"refresh_token":**null**}"

**Comment by biow0lf** [comment]
ccpgames/esi-issues#274

**Comment by bbenham** [comment]
I'm not understanding biow0lf..  
This has been working all week and just today it stopped giving me a refresh token.  That says something.
I am authorizing this scope in the authorization request:
"esi-markets.structure_markets.v1"
The same scope is also setup in my application permissions for my account.
I see no scope called "public_data" in the published list of scopes on developers.eveonline.com
Can you please clarify ?  Thanks

**Comment by biow0lf** [comment]
@bbenham I just checked, if I pass scope 'esi-skills.read_skills.v1' then I receive token and refresh token. If I omit scope at all, backend doesn't return refresh token. Its not null, it just miss in response.

**Comment by biow0lf** [comment]
I can provide example rails app with omniauth eveonline gem for testing.

**Comment by bbenham** [comment]
Strange.. it's sending me a refresh token today..  I'm not sure what to make of it.  Perhaps something temporary?  Anyway, seems to be working today. Thanks for helping Biow0lf.. much appreciate it.

**Comment by Pseudocode99** [comment]
I have the same issue. With no scopes i get always a null refresh_token
