### ISSUE TITLE
SSO token access to /corp/StarbaseList.xml.asp

### ISSUE THREAD

**Issue by eve-n0rman** [ccpgames/eveonline-third-party-documentation#257]
according to [this ](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html#scope-to-access-mask-mappings ) corporationStructuresRead doesn't map to 524288, which according to [this ](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_starbaselist.html) is needed to access /corp/StarbaseList.xml.asp.  It certainly seems like it should.

Technically, this isn't a documentation bug, it's a mapping bug, but I'm not sure where else to open this.  Feel free to redirect to the right place to get this fixed.

**Comment by polarina** [comment]
Can you check the actual mapping the XML API does when presented with that scope? I recall I added this mask to the scope mapping after the initial release of the SSO integration -- it's possible the documentation hasn't been updated yet.

**Comment by eve-n0rman** [comment]
Testing indicates it's not working.  A SSO with corporationStructuresRead  I'm using to read citadel data is generating the following when I attempt to access  /corp/StarbaseList.xml.aspx:

Error code 221: Illegal page request! Please verify the access granted by the key you are using!

**Comment by polarina** [comment]
What's the access mask presented to you by the /account/APIKeyInfo.xml.aspx endpoint? If you haven't already, you do need to specify the token's access type for corporation endpoints, that is `accessType=corporation`

https://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html#sso-access-tokens

**Comment by eve-n0rman** [comment]
Never mind!  I was granting esi-corporations.read_structures, but not corporationStructuresRead.  Forgive my badness and thanks for pointing me in the correct direction.

**Comment by eve-n0rman** [comment]
Technically, I guess this is now a documentation bug though, since it doesn't mention 524288 in the mapping, which does seem to be working, so I'll re-open in the hopes of a documentation fix.

**Comment by ccp-zoetrope** [comment]
Documentation relating to this has been merged.
