### ISSUE TITLE
Authenticated CREST and desktop applications

### ISSUE THREAD

**Issue by blitzmann** [ccpgames/eveonline-third-party-documentation#56]
The docs have a page that is currently blank for non-browser crest access. From what I've seen and discussed with others, it seems the only way to do this at the moment with the current OAUTH implementation is to use a proxy that the app developers control so that we don't give away our app auth keys and because tbe current implementation requires a callback url that is accessible. While this is a slight problem in that it requires an app to have a dedicated server for this, it's not outside the realm of possibility; but it would be helpful to see this documentation expand and maybe have examples on how to manage the connection in between.

**Comment by Regner** [comment]
It would be very helpful to have the documentation explain this. The industry standard is usually embed something like Chromium, see the new launcher, and host a page on a server somewhere else. The other option is having an embedded web server and use the the implicit grant type instead of authorization grant type. You only need the client ID for that and not the client and secret.

**Comment by Regner** [comment]
See here for a good read on how the two differ: https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2

**Comment by EricE** [comment]
"The other option is having an embedded web server and use the the implicit grant type instead of authorization grant type. You only need the client ID for that and not the client and secret."

Does CREST support this?  CREST is my first exposure to OAUTH...

**Comment by Regner** [comment]
Yes, CREST supports the implicit grant type.

**Comment by bastianh** [comment]
I think you don't need an integrated web server ... just parse the url you get back for the token

**Comment by narthollis** [comment]
You should also be able to register a URL handler, and have CREST redirect back to that. (Assuming the CREST redirect accepts non-(http|https) redirects)

Eg. Redirect to myapphandler://crestauth/?authCode=

**Comment by blitzmann** [comment]
I am posting this here as it contains a lot of good info on how to maybe approach this topic:

https://github.com/DarkFenX/Pyfa/issues/383

Within, these resources were collected:
http://wiki.oauth.net/w/page/27249271/OAuth%202%20for%20Native%20Apps
http://stackoverflow.com/questions/4419915/how-to-keep-the-oauth-consumer-secret-safe-and-how-to-react-when-its-compromis
https://developers.google.com/identity/protocols/OAuth2InstalledApp

**Comment by Regner** [comment]
Thank you very much for sharing!

**Comment by narthollis** [comment]
#149 documents 3 common methods of using OAuth2 in non-browser applications.

**Comment by blitzmann** [comment]
Excellent write up @narthollis. =)

**Comment by JimiC** [comment]
@Regner I believe this can be closed now.
