### ISSUE TITLE
Missing a section on popular external resources

### ISSUE THREAD

**Issue by Regner** [ccpgames/eveonline-third-party-documentation#6]
There should be a section similar to https://developers.eveonline.com/resource/external-resources

Open question is if the EVElopedia page should be kept there, or integrated into this documentation.

**Comment by Zifrian** [comment]
If I understand the question, I suggest removing all dev documentation from EVElopedia for consistency and in favor of a single point of reference for information.

**Comment by HelOWeen** [comment]
I agree with Zifrian. Have one topic _"3rd party developer information"_ in EVELopedia and point that to developers.eveonline.com.

But let me emphasize the important word here: remove all __dev__ documentation from EVElopedia.
The very first category _(Common Equations)_ is a good example of what should stay as its own topic. There are equations of general interest in EVE _("How's the stacking penalty calculated?")_ which should (also?) stay in the Wiki. OTOH, the only equation _(External Killmail Hash)_ currently present there is a perfect example of what should be moved into a _developer_ documentation.

**Comment by Regner** [comment]
Hey guys, really sorry about the delay on answering. This is my last day before vacation and I have been really busy this week trying to get things done before vacation. I will be back from vacation in two weeks and hopefully we can properly continue this discussion.

**Comment by polarina** [comment]
The original link is a 404. It has been moved to https://developers.eveonline.com/resource/resources.

**Comment by JimiC** [comment]
Since EVElopedia is no more. In http://eveonline-third-party-documentation.readthedocs.org/en/latest/sde/intro.html I have fixed the link of ` Static Data Export (SDE)` to lead to https://developers.eveonline.com/resource/resources.

Close?
