### ISSUE TITLE
Discussion about the left navigation

### ISSUE THREAD

**Issue by Regner** [ccpgames/eveonline-third-party-documentation#74]
Hey guys,

Just wanted to have a quick discussion about the left nav menu. It is getting pretty damn long. Are we OK with that? Does anyone possibly know of a better way to handle it? I was playing around with a few other ways to do it but wasn't really happy with anything.

**Comment by clonerworks** [comment]
Do you think something like this with the collapsible menu options work for it?

![image](https://cloud.githubusercontent.com/assets/4615641/11394741/119b7c78-93bb-11e5-9650-0fa1e93fa160.png)

**Comment by blitzmann** [comment]
More granularity would be awesome for things like database and API documentation. I thought read the docs only supported two levels of navigation though

**Comment by Regner** [comment]
I couldn't get the collapsible menu to work well on read the docs. :(

**Comment by clonerworks** [comment]
Could it be worthwhile breaking the docs into multiple repos and having multiple cross linking sites for diff sections.
EG: 
Crest (one repo)
XMl Api (another repo)
SDE (another repo)

This would allow us to add more content without having an insane navigation bar.
I have very limited knowledge of read the docs and mkdocs so don't know if there is another way of doing it.

**Comment by deadlybulb** [comment]
With mkdocs you can get part of the way there if you customize the theme.  Sphinx has fancier features for theme customization but that would be a bigger change.  I'll see if I can hack something up that we can play with, but the gist is that you can:

1. Clone the mkdocs repo from here https://github.com/mkdocs/mkdocs
2. Copy mkdocs/mkdocs/themes/readthedocs into your eveonline-third-party-documentation root (let's say you rename the directory to readthedocs_custom)
3. Edit mkdocs.yaml and add theme_dir: 'readthedocs_custom'
4. Mangle readthedocs_custom/toc.html to change how the nav bar is displayed
5. (Optional) delete all the other files out of readthedocs_custom that you don't want to edit.  In this mode, mkdocs will only apply your toc.html changes, leaving everything else the same.

It should be straightforward to hack up an "onclick" onto the header for each section which hides/shows the subsections.  Not sure how this will look on mobile, etc.

**Comment by Regner** [comment]
If possible I would rather not modify or create a theme. If we can find one we really like and it doesn't work on read the docs or whatever I will get resources for CCP to host the docs.

**Comment by JimiC** [comment]
Have a look at https://docs.asp.net/en/latest/

**Comment by deadlybulb** [comment]
Yeah if we switch to Sphinx we have more options, but Sphinx isn't quite as simple as mkdocs.  The bootswatch themes on mkdocs collapse the nav as we want, but also moves things to the top (i.e. typical bootstrap nav) which overruns the display for the number of top-level nav entries we currently have.

![screenshot](https://cloud.githubusercontent.com/assets/5150956/11443206/1ee5de94-94e9-11e5-986e-c21e9252d789.png)

**Comment by Regner** [comment]
Yea, one of the main reasons I chose mkdocks was the simplicity of it to help get as many people contributing as possible.

We could of course remove that Image Server Test link and it would all fit but we would be 100% at the limit there and if we ever wanted to expand it... well fuck.

Hmmm.....

**Comment by Regner** [comment]
All the default mkdock themes put the nav bar at the top :(

**Comment by Regner** [comment]
There doesn't seem to be any options outside the included ones for mkdoc themes

**Comment by JimiC** [comment]
Regner wrote:
>Yea, one of the main reasons I chose mkdocks was the simplicity of it to help get as many people contributing as possible.

>We could of course remove that Image Server Test link and it would all fit but we would be 100% at the limit there and if we ever wanted to expand it... well fuck.

>Hmmm.....

Personally I don't find [Sphinx](http://sphinx-doc.org/) with [reStructuredText](http://sphinx-doc.org/rest.html) (which resembles [Markdown](https://guides.github.com/features/mastering-markdown/)) harder than [mkdocs](http://www.mkdocs.org/), not to mention that it has more capabilities that suits us.

Once you have set it up, it's all the same (to me at least).

**Comment by Regner** [comment]
@clonerworks how did you get that collapsible menu? I couldn't get that to work.

**Comment by deadlybulb** [comment]
I added a PR (issue #86) which gives a simple example of adding collapsible nav to the readthedocs mkdocs theme.  I can't see any way to really do this better short of writing our own theme (which I basically did in a very simple way).

**Comment by blitzmann** [comment]
@Regner May I ask why you stated that are hesitant on modifying or creating a theme? I know next to nothing about mkdocs, so I don't know how it actually builds the documentations, but it seems to me it might be easy enough to get multiple levels of documentation topics simply based on new HTML and JavaScript

**Comment by JimiC** [comment]
Any interest into switching to Sphinx that supports [Markdown](https://guides.github.com/features/mastering-markdown/) rendering via [Recommonmark](https://recommonmark.readthedocs.org/en/latest/)?

@Regner 
I'm willing to transpose the docs to that if you agree.

**Comment by Regner** [comment]
I will look into it a bit more tomorrow but can you give a brief list of reasons why?

**Comment by JimiC** [comment]
Well, I thought this discussion was about improving the TOC list, right?. Come to thing of it again, I'm not sure how the TOC will look like with Sphinx-Recommonmark. I will have to investigate it further.

Having build EVEMon's Docs with Sphinx rST and worked with mkdocs for this project, it wouldn't be much of a hassle for me to try it out.

**Comment by deadlybulb** [comment]
The last time we discussed this, one of the issues was creating a collapsible TOC to help manage the large number of entries.  Beyond that, one of the nice things about the current setup is its accessibility to many people who don't write docs often.  If you can setup Sphinx such that most of the complexity is hidden, and adding docs still basically boils down to editing a file or two with markdown, then I think it's a winner.

**Comment by JimiC** [comment]
@deadlybulb 
That's the idea.

**Comment by JimiC** [comment]
Buggers.

Turns out `recommonmark` is unable to create TOC when link is referencing a markdown file in a folder under the top level.

i.e
`[Home](home.md)` creates a reference
`[Guidelines and References](reference/index.md)` does not

I could fiddle the [transform.py] (https://github.com/rtfd/recommonmark/blob/master/recommonmark/transform.py) of `recommonmark` to make it work locally but it will not work on RTD (it won't have the fiddled code).

This is a major blocker to transpose this project to Sphinx with markdown usage.

**Comment by JimiC** [comment]
People rejoice :joy_cat:.

I managed to have Sphinx with markdown for the eveonline-third-party-docs. Sample on how the docs look like on http://test-eveonline-third-party-documentation.readthedocs.org/

**Disclaimer:** There is still some work to be done on the links inside the pages but the majority has been done.

Though there are some good news and bad news.

### Good News
1. All goodies of Sphinx extensions are available.
2. Ability to use custom javascript and stylesheet.

### Bad News
1. Unfortunately the toc tree doesn't build locally. It builds on ReadTheDocs though. I have yet to find out how the toc builds on RTD and not locally.

@Regner 
If the ***Bad News*** are a major blocker to not accept a PR with these changes let me know asap.

**Comment by Regner** [comment]
I think that is acceptable. What are the symptoms of this? Does it effect any other formatting?

**Comment by JimiC** [comment]
Not quite sure what you means by "effect any other formatting".

**Comment by deadlybulb** [comment]
@JimiC can you point me to a repo I can clone?  or a cr?

**Comment by JimiC** [comment]
@deadlybulb I wouldn't recommend to clone my forked repo yet as I still have some work to do on it.
For the record I'm developing the docs on Windows. I'll try it also on Linux to see how it behaves there.

**Comment by deadlybulb** [comment]
Fair enough.  Happy to help if you need another pair of eyes.

**Comment by JimiC** [comment]
@deadlybulb Will leave a comment as soon as I'm finished and let you know when to clone my forked repo.

**Comment by JimiC** [comment]
I fixed the http code block highlighting. As an extra I used highlight.js as mkdocs used it also. Colors ain't matching exactly with mkdocs as it uses a github theme. If it's crucial to use the same theme as mkdocs let me know and I can switch that.

**Comment by JimiC** [comment]
@deadlybulb On the [sample docs](http://test-eveonline-third-party-documentation.readthedocs.org/) each page has a link that leads to my forked repo. You can clone that now.

@Regner I still have to figure out how to build the toc locally and then update the **Developing** section of the README file.

**Comment by Regner** [comment]
I will try and sync your fork tomorrow and take a look :)

**Comment by JimiC** [comment]
UPDATE:

Turns out that the toc tree doesn't build only on Windows.
I just test it on Linux (Ubuntu) and it's all good.

Will update the **Developing** section of README file and hopefully :shipit: a PR.

**Comment by Regner** [comment]
Weeee!

**Comment by JimiC** [comment]
I found out why the TOC fail to build on Windows. I have opened an issue on [recommonmark](https://github.com/rtfd/recommonmark/issues/39) repo and submitted a PR with a fix. If and when it gets accepted and the fix gets released, we can update the `recommonmark` requirement version and the docs can build on Windows with the TOC. (I already have it running on my Window box).

**Comment by Regner** [comment]
Awesome! I have been slowly reviewing it and hope to merge it later this week. :)

**Comment by JimiC** [comment]
BTW. You will find that I have added stub pages where there were links to non existing docs.
There shouldn't be a link in the that leads to 404, but if you find any pls let me know and I will fix it.

**Comment by JimiC** [comment]
Can we close this issue now?

**Comment by JimiC** [comment]
@polarina This is super important the `Documentation Type` needs to be switched to `Sphinx Html`. RTD is still building the docs against `MkDocs`.

**Comment by polarina** [comment]
@Regner can you please share access to readthedocs? <3

**Comment by Regner** [comment]
As soon as I am in the office tomorrow. I thought I made this change. Must have not actually hit save. :(

**Comment by Regner** [comment]
@JimiC build failing: https://readthedocs.org/projects/eveonline-third-party-documentation/builds/3888976/

Documentation type is set to Sphinx Html.

**Comment by JimiC** [comment]
@Regner It's not actually failing for the docs but for the `Latex` version of them. Will investigate and report back.

**Comment by Regner** [comment]
Thanks! If there is something I can do let me know. Would dig more into it myself but trying to get a bunch of CREST stuff done for FanFest... and I have a presentation to start. >.<

Really appreciate your help on this.

**Comment by JimiC** [comment]
You have the `Enable PDFbuild` unchecked in Admin. Try that.

**Comment by Regner** [comment]
It is already checked:
![image](https://cloud.githubusercontent.com/assets/815037/14382089/c455960e-fd7a-11e5-98ab-0f2d02115cf6.png)

**Comment by JimiC** [comment]
Aha!. But it's failing to produce the PDF version and thus the link is not available in the expandable panel. I see. Gimme some time to figure this out.

**Comment by JimiC** [comment]
Found it: `! Package inputenc Error: Unicode char \u8:★ not set up for use with LaTeX.`. We have japanese in http://eveonline-third-party-documentation.readthedocs.org/en/latest/sde/yaml/yaml_typeIDs.html 
Will look into on how to set that.

**Comment by JimiC** [comment]
@Regner For the moment you can disable the PDF build in order for the build to succeed. Still looking for a way to fix the Japanese issue in latex.

**Comment by Regner** [comment]
Done and build successful.
