### ISSUE TITLE
Search appears disabled

### ISSUE THREAD

**Issue by Gray-Lensman** [ccpgames/eveonline-third-party-documentation#96]
Is search enabled on the Eve Online 3rd party document repository?  

If not can we get it enabled, that would make the API documents much more accessible and help the contributors build a very searchable index.

Thanks.

Gray Lensman

**Comment by JimiC** [comment]
Is this still an issue?

**Comment by Gray-Lensman** [comment]
Sorry, was out of town, no, tested and works great.  Thanks.
